// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqyv7M5JIO846-EewLZwiE67cUUwrIfJo',
    appId: '1:600735072264:android:4b1f6bdb8c3c0eed7fd1bd',
    messagingSenderId: '600735072264',
    projectId: 'smatsustainsolution',
    databaseURL: 'https://smatsustainsolution-default-rtdb.firebaseio.com',
    storageBucket: 'smatsustainsolution.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuiU2jUwojXL_ln_5E6Q2L1lFzEM2L7Sk',
    appId: '1:600735072264:ios:d041a1aed1fe4b4d7fd1bd',
    messagingSenderId: '600735072264',
    projectId: 'smatsustainsolution',
    databaseURL: 'https://smatsustainsolution-default-rtdb.firebaseio.com',
    storageBucket: 'smatsustainsolution.appspot.com',
    iosClientId: '600735072264-uh5v0n61id58r3dh6745u3ai26baca8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.sSs',
  );
}
